version: '3.8'

services:
  web:
    build: ./docker/flask
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:6

  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data: